### ISSUE TITLE
CORS Patch request: Pre-flight error

### ISSUE THREAD

**Issue by philliphartin** [TheRocketLab/node-promisepay#3]
When using the ItemActions methods that use PATCH as their default transmission method (e.g. makePayment() ) I receive the following error: 

`Fetch API cannot load https://test.api.promisepay.com/items/100fd4a0-0538-11e6-b512-3e1d05defe78/make_payment. Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.`

**UPDATE**

This was when using the `node-promisepay` lib as part of an Ionic project. Issue seems to stem from the fact that during dev testing, Ionic runs it's own local dev server on `localhost:8100`. All other methods on the API work with the exception of PATCH. 

Workaround in this instance was to create a proxy alias for  'https://test.api.promisepay.com/' at `localhost:8100/api` in my project, and update the PRE_LIVE_API constant to the `localhost:8100/api` also. Whilst this is specific to my use-case, I'm not sure there is anything that can be done on your end to resolve this issue.

**Comment by Maxwell2022** [comment]
Yeah, I don't think it's an issue with the library. I used this method in production and didn't have any issues. It's linked to your dev environment setup. 
Thanks for sharing your workaround ;)
